### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by morontt** [ConstantineChe/chess#1]
Для прикола пишешь шахматы или с какой-то целью? Я года полтора тоже начал писать, но потом забил. Может напишем их и стравим друг с другом? :)

**Comment by ConstantineChe** [comment]
Я просто для обучения, и скорее френтенд для шахмат а не ИИ, и довольно
криво потому что скорее изучаю возможности, как пользоваться разніми вещими
и тому подобное.
Но может когда-нибудь и напишу ИИ

**Comment by morontt** [comment]
Эх...

**Comment by ConstantineChe** [comment]
Если интересует соревнование ИИ советую посмотреть на этот репозиторий https://github.com/thieman/korhal

**Comment by morontt** [comment]
О, благодарю. Соревнования ИИ интересуют ещё как. Вместе с кложурой. Правда на последнюю я пока забил, но это временно, т.к. лисп таки зацепил сильно.

**Comment by ConstantineChe** [comment]
В любом случае к ИИ, хоть и не в ближайшие пару месяцев точно, но вернусь.
С core.logic разобраться хотел но за разработкой чего-то такого и сейчас бы
последил.
